baseURL = "https://mgcurriculum.github.io/"
languageCode = "en-us"
title = "MakerGhat Curriculum"
theme = "hugo-digital-garden-theme"
themesdir = ""
copyright = "MakerGhat ©"

publishDir = "docs"
[params]
  name = "MakerGhat"
  description = "Transforming Education with Hands-on Learning"
  initials = ""
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "fab fa-github"

  [[params.social]]
    name = "Medium" 
    link = "#"
    icon = "fab fa-medium-m"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Blog"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Activities"
    url = "/projects/"
    weight = 2
  
  [[menu.main]]
    name = "About Us"
    url = "https://makerghat.org"
    weight = 3


[taxonomies]
tags='tags'
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'
  grade= 'grade'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'